import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="bg-blue-100">
        <div className="h-24">
          <Navigation/>
        </div>
        <div className="h-[calc(100vh-6rem)]">{children}</div>
      </div>
      </body>
      </html>
  );
}
